# Generated by Django 3.0.5 on 2020-05-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cast',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='casts',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='movie',
            new_name='book',
        ),
    ]
